name: PR from DEV to MAIN
on:
  push:
    branches: [ dev, main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev, main ]
  schedule:
    - cron: "* * * * *"
jobs:
  CloudList:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Github Pull Request
        uses: repo-sync/pull-request@master
        with:
          commit-message: scheduler pr from dev to main
          base: main
          labels: automated-pr,
          branch: dev
          delete-branch: false
