name: PR from DEV to MAIN
on:
  schedule:
  - cron: '*/5 * * * *'
jobs:
  CloudList:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Github Pull Request
        uses: repo-sync/pull-request@master
        with:
          source_branch: "main"
          destination_branch: "dev"
          pr_title: "Pulling ${{ github.ref }} into dev"
          pr_body: "crown: *An automated PR*"
          pr_allow_empty: true 
          pr_draft: false     

